### ISSUE TITLE
1.16.5，crash on startup，slf4j? log4j!

### ISSUE THREAD

**Issue by Kasualix** [PortingLab/ForgedFabricLoaderAPI#1]
![image](https://user-images.githubusercontent.com/110756250/234914049-e009b065-c465-4921-ae08-6ae9b624f62b.png)
反正你也没用到LOGGER，直接删掉得了（
@TexBlock

**Comment by TexBlock** [comment]
草，我tm怎么用的slf4j

**Comment by TexBlock** [comment]
刚发布的应该修了，
我现在在移植MiniHUD&修IngameIME-Forged，来不及测（

**Comment by Kasualix** [comment]
![image](https://user-images.githubusercontent.com/110756250/235066593-50efbc12-76dd-4463-8f8a-6cf087247d24.png)
这个前置是没问题了，但轮到投影Reforged崩了（
https://pastebin.ubuntu.com/p/4WpZdY96cm/

**Comment by Kasualix** [comment]
IChunk是接口吧（？

**Comment by TexBlock** [comment]
> ![image](https://user-images.githubusercontent.com/110756250/235066593-50efbc12-76dd-4463-8f8a-6cf087247d24.png) 这个前置是没问题了，但轮到投影Reforged崩了（ https://pastebin.ubuntu.com/p/4WpZdY96cm/

在修了，在修了.gif

**Comment by TexBlock** [comment]
> ![image](https://user-images.githubusercontent.com/110756250/235066593-50efbc12-76dd-4463-8f8a-6cf087247d24.png) 这个前置是没问题了，但轮到投影Reforged崩了（ https://pastebin.ubuntu.com/p/4WpZdY96cm/

你在https://github.com/ThinkingStudios/Litematica-Forge/issues/new发个issues吧
