### ISSUE TITLE
[1.19.2]Game crashes on startup with Rubidium

### ISSUE THREAD

**Issue by Miaochan** [PortingLab/ForgedFabricLoaderAPI#2]
ForgedFabricLoaderAPI-0.1.3-1.17_1.19与铷一同使用时游戏在启动阶段崩溃
铷版本:rubidium-0.6.2a
[错误报告-2023-4-28_17.51.27.zip](https://github.com/PortingLab/ForgedFabricLoaderAPI/files/11352309/-2023-4-28_17.51.27.zip)

**Comment by TexBlock** [comment]
与 #4 重复，将关闭此issue
