### ISSUE TITLE
[1.18.x & 1.19.x]Game crashes on startup with Rubidium

### ISSUE THREAD

**Issue by Nature0927** [PortingLab/ForgedFabricLoaderAPI#4]
ForgedFabricLoaderAPI-0.1.3-1.17_1.19与铷一同使用时游戏在启动阶段崩溃
铷版本：0.5.6
[minecraft-exported-crash-info-2023-04-28T18-20-05.zip](https://github.com/PortingLab/ForgedFabricLoaderAPI/files/11352513/minecraft-exported-crash-info-2023-04-28T18-20-05.zip)

铷版本:rubidium-0.6.2a
[错误报告-2023-4-28_17.51.27.zip](https://github.com/PortingLab/ForgedFabricLoaderAPI/files/11352309/-2023-4-28_17.51.27.zip)

**Comment by TexBlock** [comment]
应该是包名起冲突了，我一会发布个**破坏性**更新吧

**Comment by TexBlock** [comment]
在本模组更新后，您需要等待依赖此模组的模组更新之后才可使用

**Comment by TexBlock** [comment]
fixed in v0.1.4
